services:
    # Command to list available storage builders
    kryptopus_command_list_candlestick_storage_builders:
        class: "application/command/ListBuildersCommand"
        arguments:
            - "@kryptopus_candlestick_storage_builder_registry"
        tags:
            - { name: "solfege.console.command" }

    # Storage builder registry
    kryptopus_candlestick_storage_builder_registry:
        class: "domain/StorageBuilderRegistry"


